import { useState } from 'react';
import { socket } from '../socket';
import { Send, Zap, Shuffle, MessageSquare, Clipboard, RotateCcw } from 'lucide-react';

export default function TeacherView() {
    // In a real app, this code would be generated by the server
    const [joinCode] = useState('123456');
    const [promptInput, setPromptInput] = useState('');
    const [sessionState, setSessionState] = useState<'IDLE' | 'ACTIVE'>('IDLE');
    const [responsesCount, setResponsesCount] = useState(0);

    const startSession = () => {
        // Join the socket room as a teacher
        socket.auth = { role: 'TEACHER' };
        socket.connect();
        socket.emit('JOIN_ROOM', { joinCode });
        setSessionState('ACTIVE');
    };

    const sendPrompt = () => {
        if (!promptInput.trim()) return;
        socket.emit('TEACHER_SEND_PROMPT', { joinCode, content: promptInput });
        alert(`Sent prompt: "${promptInput}"`);
        setPromptInput('');
        setResponsesCount(0);
    };

    const triggerSwap = () => {
        socket.emit('TRIGGER_SWAP', { joinCode });
        alert('Swapping responses...');
    };

    const copyCode = () => {
        navigator.clipboard.writeText(joinCode).then(() => {
            alert('Join Code copied!');
        });
    }

    if (sessionState === 'IDLE') {
        return (
            <div className="flex flex-col items-center justify-center py-20">
                <h1 className="text-3xl font-bold text-gray-800 mb-6">Create New Session</h1>
                <button
                    onClick={startSession}
                    className="px-8 py-4 bg-indigo-600 text-white font-bold text-xl rounded-xl shadow-lg hover:bg-indigo-700 transition duration-200 flex items-center space-x-2"
                >
                    <Zap className="h-6 w-6" />
                    <span>Start Live Session</span>
                </button>
            </div>
        );
    }

    return (
        <div className="p-4 max-w-4xl mx-auto">
            <header className="flex flex-col sm:flex-row justify-between items-center bg-indigo-100 p-6 rounded-xl shadow-md mb-8 border-l-4 border-indigo-500">
                <h1 className="text-2xl font-bold text-indigo-800">Live Session Active</h1>
                <div className="flex items-center space-x-3 mt-4 sm:mt-0">
                    <span className="text-lg font-mono tracking-widest text-indigo-700">
                        {joinCode}
                    </span>
                    <button
                        onClick={copyCode}
                        className='p-2 bg-indigo-500 hover:bg-indigo-600 rounded-full text-white transition'
                        title='Copy Join Code'
                    >
                        <Clipboard className='w-4 h-4' />
                    </button>
                </div>
            </header>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                {/* Panel 1: Prompt Creation */}
                <div className="bg-white p-6 rounded-xl shadow-xl border-t-4 border-blue-500">
                    <h3 className="text-xl font-semibold text-blue-700 mb-4 flex items-center">
                        <MessageSquare className='w-5 h-5 mr-2' /> 1. Send Prompt
                    </h3>
                    <p className='text-gray-600 mb-4'>Enter the discussion prompt below.</p>
                    <textarea
                        value={promptInput}
                        onChange={(e) => setPromptInput(e.target.value)}
                        placeholder="Write the prompt here..."
                        rows={4}
                        className="w-full p-3 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 resize-none mb-4"
                    />
                    <button
                        onClick={sendPrompt}
                        disabled={!promptInput.trim()}
                        className="w-full flex items-center justify-center px-4 py-3 bg-blue-500 hover:bg-blue-600 text-white font-bold rounded-lg transition shadow-md"
                    >
                        <Send className='w-5 h-5 mr-2' /> Disperse Prompt
                    </button>
                </div>

                {/* Panel 2: Response Management */}
                <div className="bg-white p-6 rounded-xl shadow-xl border-t-4 border-green-500">
                    <h3 className="text-xl font-semibold text-green-700 mb-4 flex items-center">
                        <Shuffle className='w-5 h-5 mr-2' /> 2. Process Swap
                    </h3>
                    <p className="text-4xl font-extrabold text-green-600 my-4 text-center">
                        {responsesCount}
                    </p>
                    <p className='text-gray-600 mb-6 text-center'>
                        Responses Received <br /> (Simulated)
                    </p>
                    <button
                        onClick={triggerSwap}
                        disabled={responsesCount < 1} // Allow swap even with 1 for testing, though 2 is required by logic
                        className="w-full flex items-center justify-center px-4 py-3 bg-green-600 hover:bg-green-700 text-white font-bold rounded-lg transition shadow-md disabled:bg-gray-400"
                    >
                        <RotateCcw className='w-5 h-5 mr-2' /> Trigger Thought Swap
                    </button>
                </div>
            </div>

            {/* TODO: Add section for Prompt Bank / Past Prompts */}

        </div>
    );
}